name: CI

on:
  merge_group:
  pull_request:
      - 'DCO'
      - 'LICENSE'
      - 'README.md'
    branches:
      - "main"
      - "v**"
  workflow_dispatch:

jobs:
  static-security-analysis:
    runs-on: ubuntu-22.04
    env:
      GO111MODULE: on
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude-dir e2etest -severity medium ./...

      - name: Golang Vulncheck
        uses: Templum/govulncheck-action@v0.10.1
        with:
          skip-upload: true

  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5

  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Unit Tests
        run: |
          make test

      - name: Lint
        run: |
          ENV=host make lint
          make bumplicense
          go mod tidy
          make manifests
          make checkuncommitted

  build-test-images:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and export the image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: quay.io/metallb/frrk8s:dev-amd64
          file: Dockerfile
          outputs: type=docker,dest=/tmp/frrk8s.tar
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Upload frrk8s artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: image-tar-frrk8s
          path: /tmp/frrk8s.tar
